const skillData = {
    skillCategories: {
      categories: [
        "FrontEnd Technologies",
        "BackEnd Technologies",
        "DevOps Tools",
        "Cloud Services",
        "Databases",
        "Platforms / Tools",
        "Certifications",
      ],
      details: {
        "FrontEnd Technologies": [
          { name: "ReactJS", level: 90 },
          { name: "HTML", level: 90 },
          { name: "CSS", level: 90 },
          { name: "JavaScript", level: 95 },
          { name: "NextJS", level: 70 },
          { name: "Bootstrap", level: 90 },
        ],
        "BackEnd Technologies": [
          { name: "NodeJS", level: 85 },
          { name: "Java", level: 95 },
          { name: "Python", level: 90 },
          { name: "C#", level: 75 },
          { name: "Groovy", level: 90 },
          { name: "Spring Boot", level: 90 },
        ],
        "DevOps Tools": [
          { name: "Jenkins", level: 90 },
          { name: "Docker", level: 90 },
          { name: "Kubernetes", level: 90 },
          { name: "Ansible", level: 80 },
          { name: "Terraform", level: 85 },
          { name: "OpenShift", level: 90 },
          { name: "Ansible Tower", level: 95 },
        ],
        "Cloud Services": [
          { name: "AWS", level: 90 },
          { name: "Azure", level: 85 },
          { name: "GCP", level: 70 },
        ],
        Databases: [
          { name: "MySQL", level: 90 },
          { name: "MongoDB", level: 90 },
          { name: "PostgreSQL", level: 70 },
        ],
        "Platforms / Tools": [
          { name: "Git", level: 90 },
          { name: "JIRA", level: 85 },
          { name: "Dynatrace", level: 90 },
          { name: "Service Now", level: 90 },
          { name: "Postman", level: 95 },
          { name: "Linux", level: 95 },
          { name: "Powershell", level: 85 },
        ],
        Certifications: [
          "AWS Certified Cloud Practitioner",
          "AWS Certified Developer - Associate",
          "Microsoft Certified - Azure Administrator Associate",
          "Microsoft Certified - Azure Fundamentals",
          "Java Back End Developer Certified - Wipro",
          "DevOps Professional Certified - Wipro",
          "ReactJS Front End Developer Certified - Wipro",
        ],
      },
    },
    techStack: {
      categories: [
        "Languages",
        "Frameworks",
        "DevOps Tools",
        "Cloud Services",
        "Databases",
        "Tools",
        "Certifications",
      ],
      details: {
        Languages: ["Java", "Python", "JavaScript", "C#", "Groovy"],
        Frameworks: ["ReactJS", "NextJS", "NodeJS", "Spring Boot", "ExpressJS"],
        "DevOps Tools": [
          "Jenkins",
          "Docker",
          "Kubernetes",
          "Ansible",
          "Terraform",
          "OpenShift",
          "Ansible Tower",
        ],
        "Cloud Services": ["AWS", "Azure", "GCP"],
        Databases: ["MySQL", "MongoDB", "PostgreSQL"],
        Tools: [
          "Git",
          "JIRA",
          "Dynatrace",
          "Service Now",
          "Postman",
          "Linux",
          "Powershell",
        ],
        Certifications: [
          "AWS Certified Cloud Practitioner",
          "AWS Certified Developer - Associate",
          "Microsoft Certified - Azure Administrator Associate",
          "Microsoft Certified - Azure Fundamentals",
          "Java Back End Developer Certified - Wipro",
          "DevOps Professional Certified - Wipro",
          "ReactJS Front End Developer Certified - Wipro",
        ],
      },
    },
  };
  
  export default skillData;
  